### ISSUE TITLE
Crash upon /luaui reload

### ISSUE THREAD

**Issue by ghost** [Spring-SpringBoard/SpringBoard-ZK#1]
Crash when I attempted to change the skin and then /luaui reload

Infolog: http://pastebin.com/iji4f4mR

**Comment by gajop** [comment]
Well, crashes are engine issues imo, but this one seems to be related to AIs and setting cheat on/off with Scened. Try using NullAI instead (seems you're using AAI) and report back.

**Comment by ghost** [comment]
With NullAI I can now reload, but chilli theme is broken and I can't fix it by changing skin.

http://i.imgur.com/Ag2qG4R.png

**Comment by gajop** [comment]
Does it only happen with Scened ZK? Have you tried Scened BA for example?

**Comment by ghost** [comment]
I have Scened BA working, but I can't find a settings menu so I haven't
tried changing the skin.

**Comment by gajop** [comment]
SB and ZK use a separate skin now. Also there shouldn't be any major crashing.
There are still some other issues, like https://github.com/Spring-SpringBoard/SpringBoard-Core/issues/248
If you test, feel free to report in either this repo. I've added it to the main one to make the milestone tracking a bit easier.
